seed: 42
dataset: "all" #"gta" #"alderley" #"all"
work_dir: null

model:
  name: "resnet50"
  trainable_from_layer: "layer3"
  state_dict: null 

train:
  use_center_crop: false
  use_random_crop: true
  normalize: true
  n_epochs: 30
  lr: 1.e-4
  batch_size: 256

train_samples_per_place: -1 
valid_samples_per_place: -1 
