seed: 42
dataset: "gta"  #"gta" #"alderley" #"all"
work_dir: null

model:
  name: "resnet50"
  trainable_from_layer: 7     
  state_dict: "/home/lcantagallo/VPR-GTAV2Real/models/resnet50_places365.pth"  

train:
  use_center_crop: true       
  use_random_crop: false
  normalize: true
  n_epochs: 30
  lr: 1.e-4
  batch_size: 128             

train_samples_per_place: 10  
