seed: 42

dataload: "vpr"

learning_method: "infonce"  # "triplet"  #"infonce" #

train_dataset: "gta"
val_dataset: "gsv_valid"
test_dataset: "gsv_test"

work_dir: null

save_dir: "examples"
experiment: "-1"

preprocessing:
  target_height: 224
  target_width: 224
  use_center_crop: false
  use_random_crop: true
  normalize: true
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

model:
  name: "resnet50"
  trainable_from_layer: null
  state_dict: null 

train:
  n_epochs: 1
  lr: 1.e-4
  batch_size: 1

  early_stopping: true
  patience: 10
  min_delta: 0.002

  reduce_lr_on_plateau: true
  lr_factor: 0.5
  lr_patience: 3
  lr_min: 1.e-6

  weight_decay: 1.e-6
  optimizer: "adamw"

  temperature: 0.07

evaluation:
  k: 50


train_samples_per_place: 8
valid_samples_per_place: 3
contrastive_places_per_batch: 48