seed: 42

dataload: "vpr"

learning_method: "infonce"  # "triplet"  #"infonce" #

train_dataset: "gta"
val_dataset: "gsv"
test_dataset: "gsv"

work_dir: null

save_dir: "run"
experiment: "-1"

model:
  name: "resnet50"
  trainable_from_layer: null
  state_dict: null 

train:
  use_center_crop: false
  use_random_crop: true
  normalize: false
  n_epochs: 1
  lr: 1.e-4
  batch_size: 256

  early_stopping: true
  patience: 10
  min_delta: 0.002

  reduce_lr_on_plateau: true
  lr_factor: 0.5
  lr_patience: 3
  lr_min: 1.e-6

  weight_decay: 1.e-6
  optimizer: "adamw"

  temperature: 0.07

evaluation:
  k: 50


train_samples_per_place: 6
valid_samples_per_place: 3 