seed: 42

train_dataset: "gta"
val_dataset: "alderley"
test_dataset: "tokyo247"

work_dir: null

save_dir: "run"
experiment: "-1"

model:
  name: "resnet50"
  trainable_from_layer: null
  state_dict: null #"src/exp_002/places365/resnet50_places365/resnet50_places365.pth" #

train:
  use_center_crop: false
  use_random_crop: true
  normalize: false
  n_epochs: 400
  lr: 1.e-4
  batch_size: 256

  early_stopping: true
  patience: 10
  min_delta: 0.002

  reduce_lr_on_plateau: true
  lr_factor: 0.5
  lr_patience: 3
  lr_min: 1.e-6

  weight_decay: 1.e-6
  optimizer: "adamw"

evaluation:
  k: 50


train_samples_per_place: -1 
valid_samples_per_place: -1 