seed: 42

dataload: "vpr"

learning_method: "triplet"  # "triplet"  #"infonce" #

train_dataset: "gta"
val_dataset: "gsv"
test_dataset: "gsv"

work_dir: null

save_dir: "run"
experiment: "-1"

model:
  name: "resnet50"
  trainable_from_layer: null
  state_dict: null 

train:
  use_center_crop: false
  use_random_crop: true
  normalize: true
  n_epochs: 1
  lr: 1.e-4
  batch_size: 128

  early_stopping: true
  patience: 10
  min_delta: 0.002

  reduce_lr_on_plateau: true
  lr_factor: 0.5
  lr_patience: 3
  lr_min: 1.e-6

  weight_decay: 1.e-6
  optimizer: "adamw"

  temperature: 0.05

evaluation:
  k: 50


train_samples_per_place: 8
valid_samples_per_place: 4
contrastive_places_per_batch: 32