seed: 42

dataload: "vpr"
learning_method: "infonce"

train_dataset: "gta"
val_dataset: "gsv_valid"
test_dataset: "gsv_test"

work_dir: null
save_dir: "examples"
experiment: "-1"

_base_preprocessing: &base_preprocessing
  target_height: 224
  target_width: 224
  use_center_crop: false
  use_random_crop: false 
  use_random_resized_crop: false 
  use_random_grayscale: false
  use_gaussian_blur: false
  use_random_erasing: false
  use_color_jitter: false
  use_random_rotation: false
  use_gaussian_noise: false



  normalize: true
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

model:
  model_name: "resnet50"
  
  aggregator: "avg"            
  aggregator_params: {}
  
  head_type: "mlp"            
  output_dim: 2048             
  normalize_output: false      
  
  trainable_from_layer: null  
  state_dict: null

train:
  preprocessing:
    <<: *base_preprocessing
    use_random_erasing: false
    use_random_resized_crop: false
    use_random_crop: true
    use_center_crop: false
    use_horizontal_flip: false
    use_random_grayscale: false
    use_gaussian_blur: false   
    use_color_jitter: false
    use_gaussian_noise: false
    use_random_rotation: false



  n_epochs: 50
  lr: 1.e-4
  batch_size: 1

  early_stopping: true
  patience: 10
  min_delta: 0.002

  reduce_lr_on_plateau: true
  lr_factor: 0.5
  lr_patience: 3
  lr_min: 1.e-6
  weight_decay: 1.e-6

  optimizer: "adamw"

  temperature: 0.07

evaluation:
  k: 50

test:
  preprocessing:
    <<: *base_preprocessing

train_samples_per_place: 8
valid_samples_per_place: 3
contrastive_places_per_batch: 48